# Generated by Django 4.2 on 2024-12-26 07:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_author_product_like_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.models.product_image_path
            ),
        ),
    ]
